CREATE TABLE user
(U_No INT(5) PRIMARY KEY,
 U_Id VARCHAR(30) NOT NULL,
 U_Name VARCHAR(30) NOT NULL,
 U_Pw VARCHAR(30) NOT NULL,
 U_Grade VARCHAR(30) NOT NULL,
 U_Add VARCHAR(30) NOT NULL,
 U_Email VARCHAR(30) NOT NULL UNIQUE
);

ALTER TABLE member AUTO_INCREMENT=1;

CREATE TABLE page
(pageNo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pageTitle   VARCHAR(50) NOT NULL, 
pageContent VARCHAR(300) NOT NULL,
r_memberId VARCHAR(30) NOT NULL,
FOREIGN KEY(r_memberId) REFERENCES member(memberId) ON UPDATE CASCADE ON DELETE CASCADE,
pageReg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE page AUTO_INCREMENT=1;

CREATE TABLE reply
(replyNo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
r_memberId VARCHAR(30) NOT NULL,
FOREIGN KEY(r_memberId) REFERENCES member(memberId) ON UPDATE CASCADE ON DELETE CASCADE, 
replyContent   VARCHAR(300) NOT NULL,
r_pageNo INT NOT NULL,
FOREIGN KEY(r_pageNo) REFERENCES page(pageNo) ON UPDATE CASCADE ON DELETE CASCADE,
replyReg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE reply AUTO_INCREMENT=1;

CREATE TABLE reply
(replyNo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
r_pageNo INT NOT NULL,
FOREIGN KEY(r_pageNo) REFERENCES page(pageNo) ON UPDATE CASCADE ON DELETE CASCADE,
 reorder INT NOT NULL,
depth INT NOT NULL,
replyContent   VARCHAR(300) NOT NULL,
 r_memberId VARCHAR(30) NOT NULL,
FOREIGN KEY(r_memberId) REFERENCES member(memberId) ON UPDATE CASCADE ON DELETE CASCADE,
replyReg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE reply AUTO_INCREMENT=1;


ALTER TABLE reply ALTER reorder SET DEFAULT 0;
ALTER TABLE reply ALTER depth SET DEFAULT 1;


CREATE TABLE member
(memberId VARCHAR(30) PRIMARY KEY,
memberName VARCHAR(30) NOT NULL,
 memberPw VARCHAR(30) NOT NULL,
memberEmail VARCHAR(30) NOT NULL UNIQUE
);

ALTER TABLE member AUTO_INCREMENT=1;

CREATE TABLE page
(pageNo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pageTitle   VARCHAR(50) NOT NULL, 
pageContent VARCHAR(300) NOT NULL,
r_memberId VARCHAR(30) NOT NULL,
FOREIGN KEY(r_memberId) REFERENCES member(memberId) ON UPDATE CASCADE ON DELETE CASCADE,
pageReg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE page AUTO_INCREMENT=1;

CREATE TABLE reply
(replyNo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
r_memberId VARCHAR(30) NOT NULL,
FOREIGN KEY(r_memberId) REFERENCES member(memberId) ON UPDATE CASCADE ON DELETE CASCADE, 
replyContent   VARCHAR(300) NOT NULL,
r_pageNo INT NOT NULL,
FOREIGN KEY(r_pageNo) REFERENCES page(pageNo) ON UPDATE CASCADE ON DELETE CASCADE,
replyReg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE reply AUTO_INCREMENT=1;

CREATE TABLE reply
(replyNo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
r_pageNo INT NOT NULL,
FOREIGN KEY(r_pageNo) REFERENCES page(pageNo) ON UPDATE CASCADE ON DELETE CASCADE,
 reorder INT NOT NULL,
depth INT NOT NULL,
replyContent   VARCHAR(300) NOT NULL,
 r_memberId VARCHAR(30) NOT NULL,
FOREIGN KEY(r_memberId) REFERENCES member(memberId) ON UPDATE CASCADE ON DELETE CASCADE,
pre_replyNo INT DEFAULT 0,
replyReg TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE reply AUTO_INCREMENT=1;


ALTER TABLE reply ALTER reorder SET DEFAULT 0;
ALTER TABLE reply ALTER depth SET DEFAULT 1;


